### ISSUE TITLE
Error when bluff called while blocking

### ISSUE THREAD

**Issue by parabola949** [GreyWolfDev/Coup#9]
[Forwarded from Coup]
Jakson the SerialKil's turn. Jakson the SerialKil has 4 coins.
Jakson the SerialKil has chosen to steal.
Jakson the SerialKil has chosen to steal from Raúl Sarcastro [🛡 Captain]. Does anyone want to block / call bluff?
Engelbert Eric has chosen to block.  Please choose which card you are blocking with
Engelbert Eric has chosen to block Jakson the SerialKil from stealing [👳 Ambassador]. Does anyone want to call bluff?
Jakson the SerialKil has chosen to call a bluff.
Jakson the SerialKil, Engelbert Eric had 👳 Ambassador.  You must pick a card to lose!
Jakson the SerialKil has lost 👳 Ambassador.  It is now in the graveyard.
Game error: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at CoupForTelegram.Game.PlayerMadeBlockableAction(CPlayer p, Action a, CPlayer t, String cardUsed) in C:\Users\parab\Source\Repos\Coup\CoupForTelegram\CoupForTelegram\Game.cs:line 740
   at CoupForTelegram.Game.PlayerMadeBlockableAction(CPlayer p, Action a, CPlayer t, String cardUsed) in C:\Users\parab\Source\Repos\Coup\CoupForTelegram\CoupForTelegram\Game.cs:line 707
   at CoupForTelegram.Game.StartGame() in C:\Users\parab\Source\Repos\Coup\CoupForTelegram\CoupForTelegram\Game.cs:line 453

**Comment by parabola949** [comment]
Not just while blocking
[Forwarded from Coup]
Izzah [Ms Positive]'s turn. Izzah [Ms Positive] has 2 coins.
Izzah [Ms Positive] please choose an action.
Izzah [Ms Positive] has chosen to exchange cards with the deck [👳 Ambassador]. Does anyone want to call bluff?
Izzah [Ms Positive] was not blocked. Please choose your new cards in PM @coup2bot.
Game error: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at CoupForTelegram.Game.StartGame() in C:\Users\parab\Source\Repos\Coup\CoupForTelegram\CoupForTelegram\Game.cs:line 419
